// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPkVB6a9G7hsGnzmJw2Bk1jvGHNmpnrAQ',
    appId: '1:668746555795:web:61182827c4b3f670b14866',
    messagingSenderId: '668746555795',
    projectId: 'supermercado-371012',
    authDomain: 'supermercado-371012.firebaseapp.com',
    storageBucket: 'supermercado-371012.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzs9XkpjcjxlNw-Ap6n-ByN-4DL_N7So4',
    appId: '1:668746555795:android:10205d443d9abaa1b14866',
    messagingSenderId: '668746555795',
    projectId: 'supermercado-371012',
    storageBucket: 'supermercado-371012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZsqgSBEhF6tfURNZJ7zq41koTWlXJFbs',
    appId: '1:668746555795:ios:3c10f8bae79fb697b14866',
    messagingSenderId: '668746555795',
    projectId: 'supermercado-371012',
    storageBucket: 'supermercado-371012.appspot.com',
    iosClientId: '668746555795-pad23d697ia8dgffolmei743fugk2m2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hungry',
  );
}
